services:
  petclinic:
    image: petclinic-prometheus:1.0
    container_name: petclinic-prom
    networks:
      - monitoring
    ports:
      - "8080:8080"
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    depends_on: 
      - petclinic

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    networks:
      - monitoring
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data:

networks:
  monitoring: