apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: petclinic
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30950
  type: NodePort

